name: Deploy to GitHub Pages

on:
  push:
    branches:
      - custom  # 确保监听 custom 分支的推送

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.x'  # 设置为符合要求的 Node.js 版本（例如 18.x）

    - name: Install dependencies
      run: yarn install  # 使用 yarn 安装依赖

    - name: Build project
      run: yarn run build  # 使用 yarn 构建项目

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build  # 构建目录
