name: Deploy to GitHub Pages

on:
  push:
    branches:
      - custom  # 确保监听 custom 分支的推送

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.x'  # 设置 Node.js 版本为 18.x

    - name: Install dependencies
      run: yarn --cwd ./excalidraw-app install  # 在 excalidraw-app 目录中安装依赖

    - name: Build project
      run: yarn --cwd ./excalidraw-app build  # 在 excalidraw-app 目录中构建项目

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.GITHUB_TOKEN }}  # 使用 GitHub 自动生成的 token 进行认证
        publish_dir: ./excalidraw-app/build  # 发布目录指向 excalidraw-app/build
